# Generated by Django 5.1.3 on 2024-11-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseproduct",
            old_name="long_description",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="baseproduct",
            name="short_description",
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="tags",
            field=models.ManyToManyField(blank=True, to="product.tag"),
        ),
    ]
