# Generated by Django 5.1.3 on 2024-11-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_long_description_baseproduct_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseproduct",
            name="description",
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="tagline",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
