# Generated by Django 5.1.3 on 2024-11-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_baseproduct_description_baseproduct_tagline"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baseproduct",
            name="tagline",
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="sdesc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
