# Generated by Django 5.1.3 on 2024-11-08 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_baseproduct_tagline_baseproduct_sdesc"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseproduct",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
        migrations.AddField(
            model_name="baseproduct",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="product_images"),
        ),
        migrations.AddField(
            model_name="tag",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="image",
            field=models.ImageField(null=True, upload_to="product_images"),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="baseproduct",
            name="sdesc",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MinLengthValidator(200),
                    django.core.validators.MaxLengthValidator(255),
                ],
            ),
        ),
    ]
