# Generated by Django 5.1.3 on 2024-11-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_baseproduct_image_2_baseproduct_image_3_tag_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseproduct",
            old_name="image",
            new_name="image_1",
        ),
    ]
